apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amanpandey3956/todo-app.git
    targetRevision: HEAD
    path: backend-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
